/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package milas_andmetric_gastronomi_mod.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.fluids.capability.wrappers.FluidBucketWrapper;
import net.neoforged.neoforge.common.DeferredSpawnEggItem;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import milas_andmetric_gastronomi_mod.item.*;

import milas_andmetric_gastronomi_mod.MilasAndMetricGastronomyModMod;

public class MilasAndMetricGastronomyModModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(MilasAndMetricGastronomyModMod.MODID);
	public static final DeferredItem<Item> MESADEGATRONOMIA;
	public static final DeferredItem<Item> TAMAL;
	public static final DeferredItem<Item> RAVIOLI;
	public static final DeferredItem<Item> JUGODEMANZANA;
	public static final DeferredItem<Item> SALSA;
	public static final DeferredItem<Item> CARTONDEPAPAS;
	public static final DeferredItem<Item> PAPASFRITAS;
	public static final DeferredItem<Item> PINCHOS;
	public static final DeferredItem<Item> SALSAMILAS;
	public static final DeferredItem<Item> RAVIOLIMILAS;
	public static final DeferredItem<Item> JUGOMETRIC;
	public static final DeferredItem<Item> SHUSHI;
	public static final DeferredItem<Item> TAMALOTE;
	public static final DeferredItem<Item> GALLETA_XD;
	public static final DeferredItem<Item> TAZADECAFE;
	public static final DeferredItem<Item> CAFEDOBBY;
	public static final DeferredItem<Item> GRANODECAFE;
	public static final DeferredItem<Item> RODAJADEPAN;
	public static final DeferredItem<Item> SANDWICH;
	public static final DeferredItem<Item> SANDWICHJULIAN;
	public static final DeferredItem<Item> RO;
	public static final DeferredItem<Item> TOMATE;
	public static final DeferredItem<Item> CUPCAKE_MARIAJOSE;
	public static final DeferredItem<Item> PAPELDECUPCAKE_MAJO;
	public static final DeferredItem<Item> ARANDANO;
	public static final DeferredItem<Item> VINOMOXTWZL;
	public static final DeferredItem<Item> UVAS;
	public static final DeferredItem<Item> UVASBLANCAS;
	public static final DeferredItem<Item> CUBETADEUVAS;
	public static final DeferredItem<Item> CUBETADEUVASBLANCAS;
	public static final DeferredItem<Item> VINOMOXZTWL;
	public static final DeferredItem<Item> OP;
	public static final DeferredItem<Item> MEGARAVIOLIMILAS;
	public static final DeferredItem<Item> CAF;
	public static final DeferredItem<Item> CUPA;
	public static final DeferredItem<Item> VINOBE;
	public static final DeferredItem<Item> SALSAMILASFLU_BUCKET;
	public static final DeferredItem<Item> GASTRONOMIWORLD;
	public static final DeferredItem<Item> RAMEN;
	public static final DeferredItem<Item> SOPADELRAMEN;
	public static final DeferredItem<Item> FIDEOS;
	public static final DeferredItem<Item> QUESO_1;
	public static final DeferredItem<Item> MASA;
	public static final DeferredItem<Item> PIZZA_1;
	public static final DeferredItem<Item> PIEDRACONTOMATE;
	public static final DeferredItem<Item> PANQUEQUE;
	public static final DeferredItem<Item> HAMBURGUESAJULIAN;
	public static final DeferredItem<Item> JUGOMETRICDEFINITIVO;
	public static final DeferredItem<Item> RAVIOLIMILASDEFINITIVO;
	public static final DeferredItem<Item> AA_ARMOR_HELMET;
	public static final DeferredItem<Item> AA_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> AA_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> AA_ARMOR_BOOTS;
	public static final DeferredItem<Item> ARROZ;
	public static final DeferredItem<Item> BOLSADEARROZ;
	public static final DeferredItem<Item> CAFE;
	public static final DeferredItem<Item> SAL_DUST;
	public static final DeferredItem<Item> SAL_ORE;
	public static final DeferredItem<Item> SAL_BLOCK;
	public static final DeferredItem<Item> PANQUEQUES;
	public static final DeferredItem<Item> PIMIENTA;
	public static final DeferredItem<Item> SALSAMETRIC;
	public static final DeferredItem<Item> SALSAMETRICFLU_BUCKET;
	public static final DeferredItem<Item> ESPAGUETI;
	public static final DeferredItem<Item> ALBONDIGA;
	public static final DeferredItem<Item> HELADODOBBY;
	public static final DeferredItem<Item> HIELOTRITURADO;
	public static final DeferredItem<Item> RAVIOLIMILASARM_PICKAXE;
	public static final DeferredItem<Item> RAVIOLIMILASARM_AXE;
	public static final DeferredItem<Item> RAVIOLIMILASARM_SWORD;
	public static final DeferredItem<Item> RAVIOLIMILASARM_SHOVEL;
	public static final DeferredItem<Item> RAVIOLIMILASARM_HOE;
	public static final DeferredItem<Item> BLOQUEMILAS;
	public static final DeferredItem<Item> MUNDOMILAS;
	public static final DeferredItem<Item> M_SPAWN_EGG;
	public static final DeferredItem<Item> HELADODOBBYNIGER;
	public static final DeferredItem<Item> TINTEBLACK;
	public static final DeferredItem<Item> SALSAMETRICN;
	public static final DeferredItem<Item> HAMBUGESAN;
	public static final DeferredItem<Item> ALBONDIGAN;
	public static final DeferredItem<Item> PANQUEQUESN;
	public static final DeferredItem<Item> X_2;
	public static final DeferredItem<Item> ESPAN;
	public static final DeferredItem<Item> TAMALOTEN;
	public static final DeferredItem<Item> SALSAMILASN;
	public static final DeferredItem<Item> SALSAN;
	public static final DeferredItem<Item> CARTONN;
	public static final DeferredItem<Item> PAN;
	public static final DeferredItem<Item> PANN;
	public static final DeferredItem<Item> RON;
	public static final DeferredItem<Item> RAMENN;
	public static final DeferredItem<Item> X_2N;
	public static final DeferredItem<Item> XDN;
	public static final DeferredItem<Item> OPN;
	public static final DeferredItem<Item> METRICN;
	public static final DeferredItem<Item> JUGOMETRIOCN;
	public static final DeferredItem<Item> SHUSHIN;
	public static final DeferredItem<Item> PIEN;
	public static final DeferredItem<Item> PIZZAN;
	public static final DeferredItem<Item> MILASN;
	public static final DeferredItem<Item> MILASNN;
	public static final DeferredItem<Item> MILASNNN;
	public static final DeferredItem<Item> EEARMOR_HELMET;
	public static final DeferredItem<Item> EEARMOR_CHESTPLATE;
	public static final DeferredItem<Item> EEARMOR_LEGGINGS;
	public static final DeferredItem<Item> EEARMOR_BOOTS;
	public static final DeferredItem<Item> HUEVO_ARMOR_HELMET;
	public static final DeferredItem<Item> HUEVO_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> HUEVO_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> HUEVO_ARMOR_BOOTS;
	public static final DeferredItem<Item> SOYEXTRAHUEVOORDINARIO;
	public static final DeferredItem<Item> NADA;
	public static final DeferredItem<Item> PANDEPERRO;
	public static final DeferredItem<Item> COCACOLA;
	public static final DeferredItem<Item> COCAPINA;
	public static final DeferredItem<Item> JULIANCOLA;
	public static final DeferredItem<Item> PIZZAMILAS;
	public static final DeferredItem<Item> JUGODESANDIA;
	public static final DeferredItem<Item> JUGODEZANAHORIA;
	public static final DeferredItem<Item> SOPADETOMATE;
	public static final DeferredItem<Item> MD;
	public static final DeferredItem<Item> TA;
	public static final DeferredItem<Item> PINA;
	public static final DeferredItem<Item> AGUACATE;
	public static final DeferredItem<Item> LIMON;
	public static final DeferredItem<Item> LIMONADA;
	public static final DeferredItem<Item> SALCHICHA;
	public static final DeferredItem<Item> JUGO_1;
	public static final DeferredItem<Item> NARANA;
	public static final DeferredItem<Item> COCANAJA;
	public static final DeferredItem<Item> MILASCOLA;
	public static final DeferredItem<Item> S_GUACAPIDER_SPAWN_EGG;
	public static final DeferredItem<Item> GUACAMOLE;
	public static final DeferredItem<Item> PERROCALIENTEA;
	public static final DeferredItem<Item> PIZACONPUNA;
	public static final DeferredItem<Item> X_3;
	public static final DeferredItem<Item> HAMBURGUESA;
	public static final DeferredItem<Item> CCOPADEVINO;
	public static final DeferredItem<Item> COPA;
	public static final DeferredItem<Item> REYNAGUACA_SPAWN_EGG;
	public static final DeferredItem<Item> PALTA_WOOD;
	public static final DeferredItem<Item> PALTA_LOG;
	public static final DeferredItem<Item> PALTA_PLANKS;
	public static final DeferredItem<Item> PALTA_LEAVES;
	public static final DeferredItem<Item> PALTA_STAIRS;
	public static final DeferredItem<Item> PALTA_SLAB;
	public static final DeferredItem<Item> PALTA_FENCE;
	public static final DeferredItem<Item> PALTA_FENCE_GATE;
	public static final DeferredItem<Item> PALTA_PRESSURE_PLATE;
	public static final DeferredItem<Item> PALTA_BUTTON;
	public static final DeferredItem<Item> CPLAMETRUIC;
	public static final DeferredItem<Item> PASTAMILAS;
	public static final DeferredItem<Item> MILAS;
	public static final DeferredItem<Item> GUACAPIG_SPAWN_EGG;
	public static final DeferredItem<Item> CUPC;
	public static final DeferredItem<Item> A_12A;
	public static final DeferredItem<Item> PERROPITUFO;
	public static final DeferredItem<Item> OLLITA_SPAWN_EGG;
	public static final DeferredItem<Item> PIEDELIMON;
	public static final DeferredItem<Item> OLLITACCHULE_SPAWN_EGG;
	public static final DeferredItem<Item> BURBUJITO_SPAWN_EGG;
	public static final DeferredItem<Item> JAMON_SPAWN_EGG;
	public static final DeferredItem<Item> JAMONA;
	public static final DeferredItem<Item> SANDWICHLEJENDARIO;
	public static final DeferredItem<Item> CHEF_SPAWN_EGG;
	public static final DeferredItem<Item> SOPAJULIAN;
	public static final DeferredItem<Item> GOMITA;
	public static final DeferredItem<Item> CUPK;
	public static final DeferredItem<Item> PIZZADECAMMARON;
	public static final DeferredItem<Item> SHUSI;
	public static final DeferredItem<Item> A_13A;
	public static final DeferredItem<Item> COCAMANZ;
	public static final DeferredItem<Item> AGUACATEENCANTADO;
	public static final DeferredItem<Item> TOMATEDORADO;
	public static final DeferredItem<Item> GUACAMOLEREAL;
	public static final DeferredItem<Item> MAYONESA;
	public static final DeferredItem<Item> MANTEQUILLA;
	public static final DeferredItem<Item> CEBOLLA;
	public static final DeferredItem<Item> SALSATARTARA;
	public static final DeferredItem<Item> CHILE;
	public static final DeferredItem<Item> CHILEFANTASMA;
	public static final DeferredItem<Item> CHILEGELIDO;
	public static final DeferredItem<Item> CRISTAL_HELADO_INGOT;
	public static final DeferredItem<Item> CRISTAL_HELADO_ORE;
	public static final DeferredItem<Item> CRISTAL_HELADO_BLOCK;
	public static final DeferredItem<Item> TANQUECRIOGENICO;
	public static final DeferredItem<Item> MILASCHEF_SPAWN_EGG;
	public static final DeferredItem<Item> CUCHILLO;
	public static final DeferredItem<Item> CURRY;
	public static final DeferredItem<Item> TACO;
	public static final DeferredItem<Item> BURRITO;
	public static final DeferredItem<Item> TORTILLA;
	public static final DeferredItem<Item> TACOCONCHILEFANTASMA;
	public static final DeferredItem<Item> BURRITOFANTASMA;
	public static final DeferredItem<Item> CURRYFANTASMA;
	public static final DeferredItem<Item> TACOGELIDO;
	public static final DeferredItem<Item> BURRIGELIDO;
	public static final DeferredItem<Item> CURRYGELIDO;
	public static final DeferredItem<Item> DONA;
	public static final DeferredItem<Item> DONAMILAS;
	public static final DeferredItem<Item> GLACEADOITEM;
	public static final DeferredItem<Item> DONASINGLASEADO;
	public static final DeferredItem<Item> GLACEADOMILAS;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_INGOT;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_ORE;
	public static final DeferredItem<Item> CRISTALDE_CARAMELO_BLOCK;
	public static final DeferredItem<Item> CRISTALDECARAMMELO;
	public static final DeferredItem<Item> OSODEGOMA_SPAWN_EGG;
	public static final DeferredItem<Item> DONANIGHTMER;
	public static final DeferredItem<Item> A_3436756D;
	public static final DeferredItem<Item> CARAMELO;
	public static final DeferredItem<Item> MACARON;
	public static final DeferredItem<Item> MACARONJULIAN;
	public static final DeferredItem<Item> MACARONRADIOACTIVO;
	public static final DeferredItem<Item> HELADOMILAS;
	public static final DeferredItem<Item> G_UARDIAGUACA_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_2_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_3_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_4_SPAWN_EGG;
	public static final DeferredItem<Item> OSITO_5_SPAWN_EGG;
	public static final DeferredItem<Item> SALMISTICAS_DUST;
	public static final DeferredItem<Item> SALMISTICAS_ORE;
	public static final DeferredItem<Item> SALMISTICAS_BLOCK;
	public static final DeferredItem<Item> HELADO;
	public static final DeferredItem<Item> GOMITA_2;
	public static final DeferredItem<Item> GOMITA_3;
	public static final DeferredItem<Item> GOMITA_4;
	public static final DeferredItem<Item> GOMITA_5;
	public static final DeferredItem<Item> PERRONIGTHMER;
	public static final DeferredItem<Item> NAITBEAR_SPAWN_EGG;
	public static final DeferredItem<Item> SAL_2;
	public static final DeferredItem<Item> GUMMYBEAR;
	public static final DeferredItem<Item> PINCHOCOMPLETO;
	public static final DeferredItem<Item> CRISTALFUNDIDO;
	public static final DeferredItem<Item> CHILEPESADILLA;
	public static final DeferredItem<Item> HADA_DEDULCE_SPAWN_EGG;
	public static final DeferredItem<Item> CORRINPOPPER_SPAWN_EGG;
	public static final DeferredItem<Item> SWETIPOPPER_SPAWN_EGG;
	public static final DeferredItem<Item> CORRINMETRIC_SPAWN_EGG;
	public static final DeferredItem<Item> CUCHILLOFUN;
	public static final DeferredItem<Item> DUMPLINGS;
	public static final DeferredItem<Item> TEDEBOBA;
	public static final DeferredItem<Item> TEDEBOBAMETRIC;
	public static final DeferredItem<Item> BANANASPLIT;
	public static final DeferredItem<Item> BANANA;
	public static final DeferredItem<Item> SEMILLADEBOBA;
	public static final DeferredItem<Item> BOBALIQUIDA;
	public static final DeferredItem<Item> DUMPLINGVENDEDORDEBOBA_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINPEQUENO_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINGMEDIANO_SPAWN_EGG;
	public static final DeferredItem<Item> DUMPLINGRANDE_SPAWN_EGG;
	public static final DeferredItem<Item> CALAMARFRITO_SPAWN_EGG;
	public static final DeferredItem<Item> SANDWICHSALVAJE_SPAWN_EGG;
	public static final DeferredItem<Item> DURIAN;
	public static final DeferredItem<Item> CUBANO_SPAWN_EGG;
	public static final DeferredItem<Item> SATAANDAGUI;
	public static final DeferredItem<Item> CONODEHELADO_2;
	public static final DeferredItem<Item> SATAANDAGI;
	public static final DeferredItem<Item> GRANADILLAROJA;
	public static final DeferredItem<Item> BAOZI;
	public static final DeferredItem<Item> YAKI_ONIGIRI;
	public static final DeferredItem<Item> SANDWICHDULCE_SPAWN_EGG;
	public static final DeferredItem<Item> ZONGZI;
	public static final DeferredItem<Item> BOLADESESAMO;
	public static final DeferredItem<Item> GREENGRAPES;
	public static final DeferredItem<Item> PURPLEONION;
	public static final DeferredItem<Item> WHITEONION;
	public static final DeferredItem<Item> GOMITA_6;
	public static final DeferredItem<Item> LETTUCE;
	public static final DeferredItem<Item> TOMATO_STAGE_0;
	public static final DeferredItem<Item> TOMATO_STAGE_1;
	public static final DeferredItem<Item> TOMATO_STAGE_2;
	public static final DeferredItem<Item> TOMATO_STAGE_3;
	public static final DeferredItem<Item> CANDYGRASS;
	public static final DeferredItem<Item> CANDYBARPLANT;
	public static final DeferredItem<Item> OSO_6_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_2_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_3_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_4_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_5_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_6_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_7_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMOB_8_SPAWN_EGG;
	public static final DeferredItem<Item> HELADOMETRIC_SPAWN_EGG;
	public static final DeferredItem<Item> SLIME_SPAWN_EGG;
	static {
		MESADEGATRONOMIA = block(MilasAndMetricGastronomyModModBlocks.MESADEGATRONOMIA);
		TAMAL = REGISTRY.register("tamal", TamalItem::new);
		RAVIOLI = REGISTRY.register("ravioli", RavioliItem::new);
		JUGODEMANZANA = REGISTRY.register("jugodemanzana", JugodemanzanaItem::new);
		SALSA = REGISTRY.register("salsa", SalsaItem::new);
		CARTONDEPAPAS = REGISTRY.register("cartondepapas", CartondepapasItem::new);
		PAPASFRITAS = REGISTRY.register("papasfritas", PapasfritasItem::new);
		PINCHOS = REGISTRY.register("pinchos", PinchosItem::new);
		SALSAMILAS = REGISTRY.register("salsamilas", SalsamilasItem::new);
		RAVIOLIMILAS = REGISTRY.register("raviolimilas", RaviolimilasItem::new);
		JUGOMETRIC = REGISTRY.register("jugometric", JugometricItem::new);
		SHUSHI = REGISTRY.register("shushi", ShushiItem::new);
		TAMALOTE = REGISTRY.register("tamalote", TamaloteItem::new);
		GALLETA_XD = REGISTRY.register("galleta_xd", GalletaXDItem::new);
		TAZADECAFE = REGISTRY.register("tazadecafe", TazadecafeItem::new);
		CAFEDOBBY = REGISTRY.register("cafedobby", CafedobbyItem::new);
		GRANODECAFE = REGISTRY.register("granodecafe", GranodecafeItem::new);
		RODAJADEPAN = REGISTRY.register("rodajadepan", RodajadepanItem::new);
		SANDWICH = REGISTRY.register("sandwich", SandwichItem::new);
		SANDWICHJULIAN = REGISTRY.register("sandwichjulian", SandwichjulianItem::new);
		RO = REGISTRY.register("ro", RoItem::new);
		TOMATE = REGISTRY.register("tomate", TomateItem::new);
		CUPCAKE_MARIAJOSE = REGISTRY.register("cupcake_mariajose", CupcakeMariajoseItem::new);
		PAPELDECUPCAKE_MAJO = REGISTRY.register("papeldecupcake_majo", PapeldecupcakeMajoItem::new);
		ARANDANO = REGISTRY.register("arandano", ArandanoItem::new);
		VINOMOXTWZL = REGISTRY.register("vinomoxtwzl", VinomoxtwzlItem::new);
		UVAS = REGISTRY.register("uvas", UvasItem::new);
		UVASBLANCAS = REGISTRY.register("uvasblancas", UvasblancasItem::new);
		CUBETADEUVAS = REGISTRY.register("cubetadeuvas", CubetadeuvasItem::new);
		CUBETADEUVASBLANCAS = REGISTRY.register("cubetadeuvasblancas", CubetadeuvasblancasItem::new);
		VINOMOXZTWL = REGISTRY.register("vinomoxztwl", VinomoxztwlItem::new);
		OP = REGISTRY.register("op", OpItem::new);
		MEGARAVIOLIMILAS = REGISTRY.register("megaraviolimilas", MegaraviolimilasItem::new);
		CAF = REGISTRY.register("caf", CafItem::new);
		CUPA = REGISTRY.register("cupa", CupaItem::new);
		VINOBE = REGISTRY.register("vinobe", VinobeItem::new);
		SALSAMILASFLU_BUCKET = REGISTRY.register("salsamilasflu_bucket", SalsamilasfluItem::new);
		GASTRONOMIWORLD = REGISTRY.register("gastronomiworld", GastronomiworldItem::new);
		RAMEN = REGISTRY.register("ramen", RamenItem::new);
		SOPADELRAMEN = REGISTRY.register("sopadelramen", SopadelramenItem::new);
		FIDEOS = REGISTRY.register("fideos", FideosItem::new);
		QUESO_1 = REGISTRY.register("queso_1", Queso1Item::new);
		MASA = REGISTRY.register("masa", MasaItem::new);
		PIZZA_1 = REGISTRY.register("pizza_1", Pizza1Item::new);
		PIEDRACONTOMATE = REGISTRY.register("piedracontomate", PiedracontomateItem::new);
		PANQUEQUE = REGISTRY.register("panqueque", PanquequeItem::new);
		HAMBURGUESAJULIAN = REGISTRY.register("hamburguesajulian", HamburguesajulianItem::new);
		JUGOMETRICDEFINITIVO = REGISTRY.register("jugometricdefinitivo", JugometricdefinitivoItem::new);
		RAVIOLIMILASDEFINITIVO = REGISTRY.register("raviolimilasdefinitivo", RaviolimilasdefinitivoItem::new);
		AA_ARMOR_HELMET = REGISTRY.register("aa_armor_helmet", AaArmorItem.Helmet::new);
		AA_ARMOR_CHESTPLATE = REGISTRY.register("aa_armor_chestplate", AaArmorItem.Chestplate::new);
		AA_ARMOR_LEGGINGS = REGISTRY.register("aa_armor_leggings", AaArmorItem.Leggings::new);
		AA_ARMOR_BOOTS = REGISTRY.register("aa_armor_boots", AaArmorItem.Boots::new);
		ARROZ = REGISTRY.register("arroz", ArrozItem::new);
		BOLSADEARROZ = REGISTRY.register("bolsadearroz", BolsadearrozItem::new);
		CAFE = REGISTRY.register("cafe", CafeItem::new);
		SAL_DUST = REGISTRY.register("sal_dust", SalDustItem::new);
		SAL_ORE = block(MilasAndMetricGastronomyModModBlocks.SAL_ORE);
		SAL_BLOCK = block(MilasAndMetricGastronomyModModBlocks.SAL_BLOCK);
		PANQUEQUES = REGISTRY.register("panqueques", PanquequesItem::new);
		PIMIENTA = REGISTRY.register("pimienta", PimientaItem::new);
		SALSAMETRIC = REGISTRY.register("salsametric", SalsametricItem::new);
		SALSAMETRICFLU_BUCKET = REGISTRY.register("salsametricflu_bucket", SalsametricfluItem::new);
		ESPAGUETI = REGISTRY.register("espagueti", EspaguetiItem::new);
		ALBONDIGA = REGISTRY.register("albondiga", AlbondigaItem::new);
		HELADODOBBY = REGISTRY.register("heladodobby", HeladodobbyItem::new);
		HIELOTRITURADO = REGISTRY.register("hielotriturado", HielotrituradoItem::new);
		RAVIOLIMILASARM_PICKAXE = REGISTRY.register("raviolimilasarm_pickaxe", RaviolimilasarmPickaxeItem::new);
		RAVIOLIMILASARM_AXE = REGISTRY.register("raviolimilasarm_axe", RaviolimilasarmAxeItem::new);
		RAVIOLIMILASARM_SWORD = REGISTRY.register("raviolimilasarm_sword", RaviolimilasarmSwordItem::new);
		RAVIOLIMILASARM_SHOVEL = REGISTRY.register("raviolimilasarm_shovel", RaviolimilasarmShovelItem::new);
		RAVIOLIMILASARM_HOE = REGISTRY.register("raviolimilasarm_hoe", RaviolimilasarmHoeItem::new);
		BLOQUEMILAS = block(MilasAndMetricGastronomyModModBlocks.BLOQUEMILAS);
		MUNDOMILAS = REGISTRY.register("mundomilas", MundomilasItem::new);
		M_SPAWN_EGG = REGISTRY.register("m_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.M, -16724992, -16764160, new Item.Properties()));
		HELADODOBBYNIGER = REGISTRY.register("heladodobbyniger", HeladodobbynigerItem::new);
		TINTEBLACK = REGISTRY.register("tinteblack", TinteblackItem::new);
		SALSAMETRICN = REGISTRY.register("salsametricn", SalsametricnItem::new);
		HAMBUGESAN = REGISTRY.register("hambugesan", HambugesanItem::new);
		ALBONDIGAN = REGISTRY.register("albondigan", AlbondiganItem::new);
		PANQUEQUESN = REGISTRY.register("panquequesn", PanquequesnItem::new);
		X_2 = REGISTRY.register("x_2", X2Item::new);
		ESPAN = REGISTRY.register("espan", EspanItem::new);
		TAMALOTEN = REGISTRY.register("tamaloten", TamalotenItem::new);
		SALSAMILASN = REGISTRY.register("salsamilasn", SalsamilasnItem::new);
		SALSAN = REGISTRY.register("salsan", SalsanItem::new);
		CARTONN = REGISTRY.register("cartonn", CartonnItem::new);
		PAN = REGISTRY.register("pan", PanItem::new);
		PANN = REGISTRY.register("pann", PannItem::new);
		RON = REGISTRY.register("ron", RonItem::new);
		RAMENN = REGISTRY.register("ramenn", RamennItem::new);
		X_2N = REGISTRY.register("x_2n", X2nItem::new);
		XDN = REGISTRY.register("xdn", XdnItem::new);
		OPN = REGISTRY.register("opn", OpnItem::new);
		METRICN = REGISTRY.register("metricn", MetricnItem::new);
		JUGOMETRIOCN = REGISTRY.register("jugometriocn", JugometriocnItem::new);
		SHUSHIN = REGISTRY.register("shushin", ShushinItem::new);
		PIEN = REGISTRY.register("pien", PienItem::new);
		PIZZAN = REGISTRY.register("pizzan", PizzanItem::new);
		MILASN = REGISTRY.register("milasn", MilasnItem::new);
		MILASNN = REGISTRY.register("milasnn", MilasnnItem::new);
		MILASNNN = REGISTRY.register("milasnnn", MilasnnnItem::new);
		EEARMOR_HELMET = REGISTRY.register("eearmor_helmet", EearmorItem.Helmet::new);
		EEARMOR_CHESTPLATE = REGISTRY.register("eearmor_chestplate", EearmorItem.Chestplate::new);
		EEARMOR_LEGGINGS = REGISTRY.register("eearmor_leggings", EearmorItem.Leggings::new);
		EEARMOR_BOOTS = REGISTRY.register("eearmor_boots", EearmorItem.Boots::new);
		HUEVO_ARMOR_HELMET = REGISTRY.register("huevo_armor_helmet", HuevoArmorItem.Helmet::new);
		HUEVO_ARMOR_CHESTPLATE = REGISTRY.register("huevo_armor_chestplate", HuevoArmorItem.Chestplate::new);
		HUEVO_ARMOR_LEGGINGS = REGISTRY.register("huevo_armor_leggings", HuevoArmorItem.Leggings::new);
		HUEVO_ARMOR_BOOTS = REGISTRY.register("huevo_armor_boots", HuevoArmorItem.Boots::new);
		SOYEXTRAHUEVOORDINARIO = REGISTRY.register("soyextrahuevoordinario", SoyextrahuevoordinarioItem::new);
		NADA = REGISTRY.register("nada", NadaItem::new);
		PANDEPERRO = REGISTRY.register("pandeperro", PandeperroItem::new);
		COCACOLA = REGISTRY.register("cocacola", CocacolaItem::new);
		COCAPINA = REGISTRY.register("cocapina", CocapinaItem::new);
		JULIANCOLA = REGISTRY.register("juliancola", JuliancolaItem::new);
		PIZZAMILAS = REGISTRY.register("pizzamilas", PizzamilasItem::new);
		JUGODESANDIA = REGISTRY.register("jugodesandia", JugodesandiaItem::new);
		JUGODEZANAHORIA = REGISTRY.register("jugodezanahoria", JugodezanahoriaItem::new);
		SOPADETOMATE = REGISTRY.register("sopadetomate", SopadetomateItem::new);
		MD = REGISTRY.register("md", MdItem::new);
		TA = REGISTRY.register("ta", TaItem::new);
		PINA = REGISTRY.register("pina", PinaItem::new);
		AGUACATE = REGISTRY.register("aguacate", AguacateItem::new);
		LIMON = REGISTRY.register("limon", LimonItem::new);
		LIMONADA = REGISTRY.register("limonada", LimonadaItem::new);
		SALCHICHA = REGISTRY.register("salchicha", SalchichaItem::new);
		JUGO_1 = REGISTRY.register("jugo_1", Jugo1Item::new);
		NARANA = REGISTRY.register("narana", NaranaItem::new);
		COCANAJA = REGISTRY.register("cocanaja", CocanajaItem::new);
		MILASCOLA = REGISTRY.register("milascola", MilascolaItem::new);
		S_GUACAPIDER_SPAWN_EGG = REGISTRY.register("s_guacapider_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.S_GUACAPIDER, -16777216, -16764160, new Item.Properties()));
		GUACAMOLE = REGISTRY.register("guacamole", GuacamoleItem::new);
		PERROCALIENTEA = REGISTRY.register("perrocalientea", PerrocalienteaItem::new);
		PIZACONPUNA = REGISTRY.register("pizaconpuna", PizaconpunaItem::new);
		X_3 = REGISTRY.register("x_3", X3Item::new);
		HAMBURGUESA = REGISTRY.register("hamburguesa", HamburguesaItem::new);
		CCOPADEVINO = REGISTRY.register("ccopadevino", CcopadevinoItem::new);
		COPA = REGISTRY.register("copa", CopaItem::new);
		REYNAGUACA_SPAWN_EGG = REGISTRY.register("reynaguaca_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.REYNAGUACA, -16764160, -13369549, new Item.Properties()));
		PALTA_WOOD = block(MilasAndMetricGastronomyModModBlocks.PALTA_WOOD);
		PALTA_LOG = block(MilasAndMetricGastronomyModModBlocks.PALTA_LOG);
		PALTA_PLANKS = block(MilasAndMetricGastronomyModModBlocks.PALTA_PLANKS);
		PALTA_LEAVES = block(MilasAndMetricGastronomyModModBlocks.PALTA_LEAVES);
		PALTA_STAIRS = block(MilasAndMetricGastronomyModModBlocks.PALTA_STAIRS);
		PALTA_SLAB = block(MilasAndMetricGastronomyModModBlocks.PALTA_SLAB);
		PALTA_FENCE = block(MilasAndMetricGastronomyModModBlocks.PALTA_FENCE);
		PALTA_FENCE_GATE = block(MilasAndMetricGastronomyModModBlocks.PALTA_FENCE_GATE);
		PALTA_PRESSURE_PLATE = block(MilasAndMetricGastronomyModModBlocks.PALTA_PRESSURE_PLATE);
		PALTA_BUTTON = block(MilasAndMetricGastronomyModModBlocks.PALTA_BUTTON);
		CPLAMETRUIC = REGISTRY.register("cplametruic", CplametruicItem::new);
		PASTAMILAS = REGISTRY.register("pastamilas", PastamilasItem::new);
		MILAS = REGISTRY.register("milas", MilasItem::new);
		GUACAPIG_SPAWN_EGG = REGISTRY.register("guacapig_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.GUACAPIG, -16777216, -13369549, new Item.Properties()));
		CUPC = REGISTRY.register("cupc", CupcItem::new);
		A_12A = REGISTRY.register("a_12a", A12aItem::new);
		PERROPITUFO = REGISTRY.register("perropitufo", PerropitufoItem::new);
		OLLITA_SPAWN_EGG = REGISTRY.register("ollita_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OLLITA, -10066330, -1, new Item.Properties()));
		PIEDELIMON = REGISTRY.register("piedelimon", PiedelimonItem::new);
		OLLITACCHULE_SPAWN_EGG = REGISTRY.register("ollitacchule_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OLLITACCHULE, -62709, -12320768, new Item.Properties()));
		BURBUJITO_SPAWN_EGG = REGISTRY.register("burbujito_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.BURBUJITO, -65536, -13369345, new Item.Properties()));
		JAMON_SPAWN_EGG = REGISTRY.register("jamon_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.JAMON, -39322, -39322, new Item.Properties()));
		JAMONA = REGISTRY.register("jamona", JamonaItem::new);
		SANDWICHLEJENDARIO = REGISTRY.register("sandwichlejendario", SandwichlejendarioItem::new);
		CHEF_SPAWN_EGG = REGISTRY.register("chef_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.CHEF, -1, -16777216, new Item.Properties()));
		SOPAJULIAN = REGISTRY.register("sopajulian", SopajulianItem::new);
		GOMITA = REGISTRY.register("gomita", GomitaItem::new);
		CUPK = REGISTRY.register("cupk", CupkItem::new);
		PIZZADECAMMARON = REGISTRY.register("pizzadecammaron", PizzadecammaronItem::new);
		SHUSI = REGISTRY.register("shusi", ShusiItem::new);
		A_13A = REGISTRY.register("a_13a", A13aItem::new);
		COCAMANZ = REGISTRY.register("cocamanz", CocamanzItem::new);
		AGUACATEENCANTADO = REGISTRY.register("aguacateencantado", AguacateencantadoItem::new);
		TOMATEDORADO = REGISTRY.register("tomatedorado", TomatedoradoItem::new);
		GUACAMOLEREAL = REGISTRY.register("guacamolereal", GuacamolerealItem::new);
		MAYONESA = REGISTRY.register("mayonesa", MayonesaItem::new);
		MANTEQUILLA = REGISTRY.register("mantequilla", MantequillaItem::new);
		CEBOLLA = REGISTRY.register("cebolla", CebollaItem::new);
		SALSATARTARA = REGISTRY.register("salsatartara", SalsatartaraItem::new);
		CHILE = REGISTRY.register("chile", ChileItem::new);
		CHILEFANTASMA = REGISTRY.register("chilefantasma", ChilefantasmaItem::new);
		CHILEGELIDO = REGISTRY.register("chilegelido", ChilegelidoItem::new);
		CRISTAL_HELADO_INGOT = REGISTRY.register("cristal_helado_ingot", CristalHeladoIngotItem::new);
		CRISTAL_HELADO_ORE = block(MilasAndMetricGastronomyModModBlocks.CRISTAL_HELADO_ORE);
		CRISTAL_HELADO_BLOCK = block(MilasAndMetricGastronomyModModBlocks.CRISTAL_HELADO_BLOCK);
		TANQUECRIOGENICO = REGISTRY.register("tanquecriogenico", TanquecriogenicoItem::new);
		MILASCHEF_SPAWN_EGG = REGISTRY.register("milaschef_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.MILASCHEF, -13369600, -16777216, new Item.Properties()));
		CUCHILLO = REGISTRY.register("cuchillo", CuchilloItem::new);
		CURRY = REGISTRY.register("curry", CurryItem::new);
		TACO = REGISTRY.register("taco", TacoItem::new);
		BURRITO = REGISTRY.register("burrito", BurritoItem::new);
		TORTILLA = REGISTRY.register("tortilla", TortillaItem::new);
		TACOCONCHILEFANTASMA = REGISTRY.register("tacoconchilefantasma", TacoconchilefantasmaItem::new);
		BURRITOFANTASMA = REGISTRY.register("burritofantasma", BurritofantasmaItem::new);
		CURRYFANTASMA = REGISTRY.register("curryfantasma", CurryfantasmaItem::new);
		TACOGELIDO = REGISTRY.register("tacogelido", TacogelidoItem::new);
		BURRIGELIDO = REGISTRY.register("burrigelido", BurrigelidoItem::new);
		CURRYGELIDO = REGISTRY.register("currygelido", CurrygelidoItem::new);
		DONA = REGISTRY.register("dona", DonaItem::new);
		DONAMILAS = REGISTRY.register("donamilas", DonamilasItem::new);
		GLACEADOITEM = REGISTRY.register("glaceadoitem", GlaceadoitemItem::new);
		DONASINGLASEADO = REGISTRY.register("donasinglaseado", DonasinglaseadoItem::new);
		GLACEADOMILAS = REGISTRY.register("glaceadomilas", GlaceadomilasItem::new);
		CRISTALDE_CARAMELO_INGOT = REGISTRY.register("cristalde_caramelo_ingot", CristaldeCarameloIngotItem::new);
		CRISTALDE_CARAMELO_ORE = block(MilasAndMetricGastronomyModModBlocks.CRISTALDE_CARAMELO_ORE);
		CRISTALDE_CARAMELO_BLOCK = block(MilasAndMetricGastronomyModModBlocks.CRISTALDE_CARAMELO_BLOCK);
		CRISTALDECARAMMELO = REGISTRY.register("cristaldecarammelo", CristaldecarammeloItem::new);
		OSODEGOMA_SPAWN_EGG = REGISTRY.register("osodegoma_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSODEGOMA, -16711936, -16751053, new Item.Properties()));
		DONANIGHTMER = REGISTRY.register("donanightmer", DonanightmerItem::new);
		A_3436756D = REGISTRY.register("a_3436756d", A3436756dItem::new);
		CARAMELO = REGISTRY.register("caramelo", CarameloItem::new);
		MACARON = REGISTRY.register("macaron", MacaronItem::new);
		MACARONJULIAN = REGISTRY.register("macaronjulian", MacaronjulianItem::new);
		MACARONRADIOACTIVO = REGISTRY.register("macaronradioactivo", MacaronradioactivoItem::new);
		HELADOMILAS = REGISTRY.register("heladomilas", HeladomilasItem::new);
		G_UARDIAGUACA_SPAWN_EGG = REGISTRY.register("g_uardiaguaca_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.G_UARDIAGUACA, -14343132, -16703487, new Item.Properties()));
		OSITO_2_SPAWN_EGG = REGISTRY.register("osito_2_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_2, -52480, -65536, new Item.Properties()));
		OSITO_3_SPAWN_EGG = REGISTRY.register("osito_3_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_3, -16724788, -16763956, new Item.Properties()));
		OSITO_4_SPAWN_EGG = REGISTRY.register("osito_4_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_4, -6711040, -256, new Item.Properties()));
		OSITO_5_SPAWN_EGG = REGISTRY.register("osito_5_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSITO_5, -16777216, -13421773, new Item.Properties()));
		SALMISTICAS_DUST = REGISTRY.register("salmisticas_dust", SalmisticasDustItem::new);
		SALMISTICAS_ORE = block(MilasAndMetricGastronomyModModBlocks.SALMISTICAS_ORE);
		SALMISTICAS_BLOCK = block(MilasAndMetricGastronomyModModBlocks.SALMISTICAS_BLOCK);
		HELADO = REGISTRY.register("helado", HeladoItem::new);
		GOMITA_2 = REGISTRY.register("gomita_2", Gomita2Item::new);
		GOMITA_3 = REGISTRY.register("gomita_3", Gomita3Item::new);
		GOMITA_4 = REGISTRY.register("gomita_4", Gomita4Item::new);
		GOMITA_5 = REGISTRY.register("gomita_5", Gomita5Item::new);
		PERRONIGTHMER = REGISTRY.register("perronigthmer", PerronigthmerItem::new);
		NAITBEAR_SPAWN_EGG = REGISTRY.register("naitbear_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.NAITBEAR, -16777216, -13421773, new Item.Properties()));
		SAL_2 = REGISTRY.register("sal_2", Sal2Item::new);
		GUMMYBEAR = REGISTRY.register("gummybear", GummybearItem::new);
		PINCHOCOMPLETO = REGISTRY.register("pinchocompleto", PinchocompletoItem::new);
		CRISTALFUNDIDO = REGISTRY.register("cristalfundido", CristalfundidoItem::new);
		CHILEPESADILLA = REGISTRY.register("chilepesadilla", ChilepesadillaItem::new);
		HADA_DEDULCE_SPAWN_EGG = REGISTRY.register("hada_dedulce_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HADA_DEDULCE, -1171524, -194423, new Item.Properties()));
		CORRINPOPPER_SPAWN_EGG = REGISTRY.register("corrinpopper_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.CORRINPOPPER, -205, -16724992, new Item.Properties()));
		SWETIPOPPER_SPAWN_EGG = REGISTRY.register("swetipopper_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.SWETIPOPPER, -205, -26368, new Item.Properties()));
		CORRINMETRIC_SPAWN_EGG = REGISTRY.register("corrinmetric_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.CORRINMETRIC, -13369396, -26215, new Item.Properties()));
		CUCHILLOFUN = REGISTRY.register("cuchillofun", CuchillofunItem::new);
		DUMPLINGS = REGISTRY.register("dumplings", DumplingsItem::new);
		TEDEBOBA = REGISTRY.register("tedeboba", TedebobaItem::new);
		TEDEBOBAMETRIC = REGISTRY.register("tedebobametric", TedebobametricItem::new);
		BANANASPLIT = REGISTRY.register("bananasplit", BananasplitItem::new);
		BANANA = REGISTRY.register("banana", BananaItem::new);
		SEMILLADEBOBA = REGISTRY.register("semilladeboba", SemilladebobaItem::new);
		BOBALIQUIDA = REGISTRY.register("bobaliquida", BobaliquidaItem::new);
		DUMPLINGVENDEDORDEBOBA_SPAWN_EGG = REGISTRY.register("dumplingvendedordeboba_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGVENDEDORDEBOBA, -2351, -4939, new Item.Properties()));
		DUMPLINPEQUENO_SPAWN_EGG = REGISTRY.register("dumplinpequeno_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINPEQUENO, -2351, -4939, new Item.Properties()));
		DUMPLINGMEDIANO_SPAWN_EGG = REGISTRY.register("dumplingmediano_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGMEDIANO, -2351, -4939, new Item.Properties()));
		DUMPLINGRANDE_SPAWN_EGG = REGISTRY.register("dumplingrande_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.DUMPLINGRANDE, -2351, -4939, new Item.Properties()));
		CALAMARFRITO_SPAWN_EGG = REGISTRY.register("calamarfrito_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.CALAMARFRITO, -26368, -13312, new Item.Properties()));
		SANDWICHSALVAJE_SPAWN_EGG = REGISTRY.register("sandwichsalvaje_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.SANDWICHSALVAJE, -11258623, -13041920, new Item.Properties()));
		DURIAN = REGISTRY.register("durian", DurianItem::new);
		CUBANO_SPAWN_EGG = REGISTRY.register("cubano_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.CUBANO, -11762905, -9744619, new Item.Properties()));
		SATAANDAGUI = REGISTRY.register("sataandagui", SataandaguiItem::new);
		CONODEHELADO_2 = REGISTRY.register("conodehelado_2", Conodehelado2Item::new);
		SATAANDAGI = REGISTRY.register("sataandagi", SataandagiItem::new);
		GRANADILLAROJA = REGISTRY.register("granadillaroja", GranadillarojaItem::new);
		BAOZI = REGISTRY.register("baozi", BaoziItem::new);
		YAKI_ONIGIRI = REGISTRY.register("yaki_onigiri", YakiOnigiriItem::new);
		SANDWICHDULCE_SPAWN_EGG = REGISTRY.register("sandwichdulce_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.SANDWICHDULCE, -8890851, -26215, new Item.Properties()));
		ZONGZI = REGISTRY.register("zongzi", ZongziItem::new);
		BOLADESESAMO = REGISTRY.register("boladesesamo", BoladesesamoItem::new);
		GREENGRAPES = REGISTRY.register("greengrapes", GreengrapesItem::new);
		PURPLEONION = REGISTRY.register("purpleonion", PurpleonionItem::new);
		WHITEONION = REGISTRY.register("whiteonion", WhiteonionItem::new);
		GOMITA_6 = REGISTRY.register("gomita_6", Gomita6Item::new);
		LETTUCE = REGISTRY.register("lettuce", LettuceItem::new);
		TOMATO_STAGE_0 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_0);
		TOMATO_STAGE_1 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_1);
		TOMATO_STAGE_2 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_2);
		TOMATO_STAGE_3 = block(MilasAndMetricGastronomyModModBlocks.TOMATO_STAGE_3);
		CANDYGRASS = block(MilasAndMetricGastronomyModModBlocks.CANDYGRASS);
		CANDYBARPLANT = block(MilasAndMetricGastronomyModModBlocks.CANDYBARPLANT);
		OSO_6_SPAWN_EGG = REGISTRY.register("oso_6_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.OSO_6, -1, -2236963, new Item.Properties()));
		HELADOMOB_SPAWN_EGG = REGISTRY.register("heladomob_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB, -5144498, -4731, new Item.Properties()));
		HELADOMOB_2_SPAWN_EGG = REGISTRY.register("heladomob_2_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_2, -5144498, -10079488, new Item.Properties()));
		HELADOMOB_3_SPAWN_EGG = REGISTRY.register("heladomob_3_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_3, -5144498, -52480, new Item.Properties()));
		HELADOMOB_4_SPAWN_EGG = REGISTRY.register("heladomob_4_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_4, -5144498, -39322, new Item.Properties()));
		HELADOMOB_5_SPAWN_EGG = REGISTRY.register("heladomob_5_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_5, -5144498, -13369345, new Item.Properties()));
		HELADOMOB_6_SPAWN_EGG = REGISTRY.register("heladomob_6_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_6, -5144498, -13369600, new Item.Properties()));
		HELADOMOB_7_SPAWN_EGG = REGISTRY.register("heladomob_7_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_7, -5144498, -13261, new Item.Properties()));
		HELADOMOB_8_SPAWN_EGG = REGISTRY.register("heladomob_8_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMOB_8, -5144498, -3394561, new Item.Properties()));
		HELADOMETRIC_SPAWN_EGG = REGISTRY.register("heladometric_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.HELADOMETRIC, -5144498, -13369447, new Item.Properties()));
		SLIME_SPAWN_EGG = REGISTRY.register("slime_spawn_egg", () -> new DeferredSpawnEggItem(MilasAndMetricGastronomyModModEntities.SLIME, -13421773, -16777216, new Item.Properties()));
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), SALSAMILASFLU_BUCKET.get());
		event.registerItem(Capabilities.FluidHandler.ITEM, (stack, context) -> new FluidBucketWrapper(stack), SALSAMETRICFLU_BUCKET.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}